name: project-ci-cd

on:
  push:
    branches:
      - dev

jobs:
  ci-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Download dependencies (at least 9000, because javascript)
        run: npm install

      - name: Run tests
        run: npm run test

  cd-backend:
    runs-on: ubuntu-latest
    needs: ci-backend
    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

  ci-frontend:
    needs: cd-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:6969'
        env:
          REACT_APP_MAIN_SERVER_URL: https://change.me

  cd-frontend:
    needs: [cd-backend, ci-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: dummy step
        run: echo TODO
